### ISSUE TITLE
[fix] 절대경로 whitelabel 에러 해결

### ISSUE THREAD

**Issue by akh9804** [kiworkshop/snowball#159]

**Comment by taesikyoo** [comment]
[스프링부트 기본 에러 페이지 변경하기 - Customize Whitelabel Error Page](
https://blog.advenoh.pe.kr/spring/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EA%B8%B0%EB%B3%B8-%EC%98%A4%EB%A5%98-%ED%8E%98%EC%9D%B4%EC%A7%80-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0/)
