### ISSUE TITLE
도메인 설계 변경 및 StockDetail 도메인 추가

### ISSUE THREAD

**Issue by taesikyoo** [kiworkshop/snowball#88]
- 기존의 보유주식, 포트폴리오 도메인 제거
- StockTransaction을 entity로 변경
- StockDetail 도메인 추가

- StockDetail에 들어갈 정보
https://docs.google.com/spreadsheets/d/1ltB1_gX3H8HVX9gyJRhVuZMafAlZFKyB_59OC6jbv0w/edit?usp=sharing

**Comment by harrisleesh** [comment]
![image](https://user-images.githubusercontent.com/29927233/97108932-f197b180-1713-11eb-8623-8f7ccbf33050.png)
![image](https://user-images.githubusercontent.com/29927233/97109148-e3966080-1714-11eb-83c0-dee7604df07e.png)

**Comment by harrisleesh** [comment]
노트를 작성하면 List\<StockTransaction\>를 노트 내부의 값 객체로 갖게 됩니다.
그리고 이 List\<StockTransaction\> 이 보유주식 객체인 Holding에 반영이되어야할 것 같아요!
이 List<Holding>을 Portfolio에서 보여줘야 하는데 이 부분을 설계하는데 고민 중입니다.

**Comment by taesikyoo** [comment]
@kwangilcho 현재까지의 설계입니다!~~

**Comment by taesikyoo** [comment]
저도 [다이어그램](https://drive.google.com/file/d/1nagOrXbnAonSuKrRAI8XkNEp3L5sTwuu/view?usp=sharing) 그려봤어요!

**Comment by taesikyoo** [comment]
https://www.notion.so/snowballapp/6b8f349001b14656be79a40f4f75b132
변경된 설계입니다~
